#! /bin/sh

mobius()
{
        echo -e '\033[33m****************Mobius info ******************\033[0m'
        rpm -qa | grep mobius
}

liberty()
{
        echo -e '\033[32m****************Liberty info ******************\033[0m'
        rpm -aq | grep liberty
}

nbserver()
{
        echo -e '\033[31m****************Nbserver info ******************\033[0m'
        rpm -aq | grep nbserver
}

libncdb()
{
        echo -e '\033[34m****************Libncdb info ******************\033[0m'
        rpm -aq | grep libncdb
}


if [ -x $1 ]
then
        mobius
        liberty
        nbserver
	libncdb
else
        if [ $1 == 0 ]
        then
                mobius
        fi
        if [ $1 == 1 ]
        then
                liberty
        fi
        if [ $1 == 2 ]
        then
                nbserver
        fi
        if [ $1 == 3 ]
        then
                libncdb
        fi
fi
