#!/bin/sh
# multiplication

num='1 2 3 4 5 6 7 8 9'
for i in $num #1 2 3 4 5 6 7 8 9
do
  for j in $num #1 2 3 4 5 6 7 8 9
  do
    if [ $j -le $i ]
    then
      echo -e "$j\c"
      echo -e "*\c"
      echo -e "$i=\c"
      echo -e "$[ $j*$i ] \c"
    fi
  done
  echo ""
done

